server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name abnsila.42.fr;

    # Matching the exact path created by the initialization script  a   
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Secure protocols mandated by Inception
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Webroot configurations
    root /var/www/html;
    index index.php index.html index.htm;

    # This line is Nginx's "fallback checker." It tells Nginx to look for files in a specific order, from left to right.
    # If it finds one, it stops and serves it. If not, it moves to the next.
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        
        # This line uses a Regular Expression (Regex) to split a URL into two distinct parts when dealing with PHP files.
        # "This is the script you need to execute (.+\.php).      "($fastcgi_script_name)
        # "This is the extra path information passed to it (/.+). "($fastcgi_path_info)
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # Check if the file actually exists before passing it to PHP-FPM
        try_files $uri =404;

        # Pass the request to the 'wordpress' container on port 9000
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;

        # Include Nginx's default FastCGI parameters
        include fastcgi_params;

        # Script name and path info extracted from fastcgi_split_path_info phase
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
