services:

  mariadb:
    build: ./requirements/mariadb
    image: "mariadb"
    container_name: mariadb
    secrets:
      - db_password
      - db_root_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - inception_net
    volumes:
      - mariadb_vol:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p$$(cat /run/secrets/db_root_password)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    image: "wordpress"
    container_name: wordpress
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_EMAIL: ${WP_EMAIL}
    networks:
      - inception_net
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: "nginx"
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    networks:
      - inception_net
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - wordpress

  redis:
    build: ./requirements/bonus/redis
    image: "redis"
    container_name: redis
    restart: unless-stopped
    networks:
      - inception_net
    volumes:
      - redis_vol:/data

  portfolio:
    image: "portfolio"
    container_name: portfolio
    build: ./requirements/bonus/protofolio
    networks:
      - inception_net
    environment:
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=${DOMAIN_NAME}
    restart: unless-stopped

  ftp:
    build: ./requirements/bonus/ftp
    image: "ftp"
    container_name: ftp
    secrets:
      - ftp_password
    environment:
      - FTP_USER=${FTP_USER}
    ports:
      - "21:21"
      - "30000-30005:30000-30005"
    networks:
      - inception_net
    volumes:
      - wordpress_vol:/var/www/html
    restart: unless-stopped

  adminer:
    build: ./requirements/bonus/adminer
    image: "adminer"
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - inception_net
    depends_on:
      - mariadb
    restart: unless-stopped

  portainer:
    build: ./requirements/bonus/portainer
    image: "portainer"
    container_name: portainer
    ports:
      - 9000:9000
    networks:
      - inception_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_vol:/data
    restart: unless-stopped

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt

networks:
  inception_net:
    name: inception_net

volumes:
  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/abnsila/data/wordpress'
  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/abnsila/data/mariadb'
  redis_vol:
    name: redis_vol
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/abnsila/data/redis'
  portainer_vol:
    name: portainer_vol
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/abnsila/data/portainer'
    