# FROM python:latest

# WORKDIR /app

# COPY requirements.txt .

# RUN pip install -r requirements.txt

# COPY hello.py .

# EXPOSE 5000

# CMD python hello.py

FROM ubuntu:latest

RUN groupadd inception && useradd -g inception abnsila
USER abnsila
RUN id
