# Run in standalone mode in the foreground
listen=YES
background=NO

# Account controls
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

# Chroot Jail configuration
chroot_local_user=YES
allow_writeable_chroot=YES

# Crucial Alpine-specific fixes
seccomp_sandbox=NO
secure_chroot_dir=/var/run/vsftpd/empty

# Docker Passive Mode Networking configurations
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30005
pasv_address=127.0.0.1

# Log collection streams
xferlog_enable=YES
vsftpd_log_file=/var/log/vsftpd.log